target-version = "py312"
line-length = 88

[lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM"]
ignore = ["SIM105"]

[lint.per-file-ignores]
"tests/**" = ["S101", "E501", "E402"]
"pyogero/const.py" = ["E501"]
"pyogero/__init__.py" = ["F401"]
"pyogero/asyncio/__init__.py" = ["F401"]
